---
- hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  roles:
  tasks:

  - name:
    raw: apt-get update && apt-get install -y  python2.7
    tags: [ "aws" ]

- hosts: all
  become: true
  become_method: sudo
  roles:
  tasks:

  # Prerequisites
  - name: If debian or ubuntu, apt-get update
    apt: update_cache=yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    tags: [ "package" ]

  - name: install the dependencies
    package: name={{item}} state=present
    with_items:
      - python
      - python-openssl
      - python-gevent
      - libevent-dev
      - python-dev
      - python-dateutil
      - python-mysqldb
      - build-essential
      - make
      - python-argparse
      - python-chardet
      - python-requests
      - python-sqlalchemy
      - python-lxml
      - python-beautifulsoup
      - python-pip
      - python-dev
      - python-setuptools
      - g++
      - git
      - php
      - php-dev
      - liblapack-dev
      - gfortran
      - cython
      - libxml2-dev
      - libxslt-dev
      - libmysqlclient-dev
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    tags: [ "package" ]

  - name: install distrubute
    command: pip install --upgrade distribute

  - name: Download BFR from github
    git:
      repo=git://github.com/mushorg/BFR.git
      dest=/opt/BFR
    register: bfr

  - name: Make BFR
    shell: "{{item}}"
    args:
      chdir: /opt/BFR/
    with_items:
      - phpize
      - ./configure --enable-bfr
      - make
      - make install
    when: bfr.changed

  - name: Find bfr.so path
    shell: updatedb && locate bfr.so | grep usr
    register: bfr_path
    when: bfr.changed

  - name: Generate php.ini
    template:
      src=templates/php.ini.j2
      dest=/etc/php/7.0/cli/php.ini
      owner=root
      group=root
      mode=0600
    when: bfr.changed

  - name: Download glastopf from github
    git:
      repo=https://github.com/mushorg/glastopf.git
      dest=/opt/glastopf
    register: glastopf

  - name: Install glastopf
    shell: python setup.py install
    args:
      chdir: /opt/glastopf
    when: glastopf.changed

  - name: Configure glastopf environment
    file:
      path=/opt/myhoneypot
      state=directory
      mode=0755

  - name: Start glastopf-runner (IGNORE ERRORS)
    become: false
    ignore_errors: yes
    shell: nohup /usr/bin/python /usr/local/bin/glastopf-runner &
    args:
      executable: /bin/bash
      chdir: /opt/myhoneypot
    poll: 0
